@url = http://localhost:8080/api/pokemon/

### GET
### User
GET {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwb2tlbW9uLXNhZmFyaSIsInN1YiI6InVzZXIxMjMiLCJhdXRob3JpdGllcyI6IlJPTEVfdXNlciIsImV4cCI6MTcyNzM0OTM2NX0.iBT8FuGeUM9IiJlccJX-1ed-SFiEwH3k6_HRuN8MRtI
### Admin
GET {{url}}admin/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwb2tlbW9uLXNhZmFyaSIsInN1YiI6ImFkbWludXNlcm5hbWUiLCJhdXRob3JpdGllcyI6IlJPTEVfYWRtaW4iLCJleHAiOjE3MjczNTc3MDN9.zTlIgL3uO7v1JFA6jlES79im8dqTCDEy_gwMb85lwwk

### Admin
GET {{url}}admin/3 HTTP/1.1

### Non ExistentUser
GET {{url}}user/22 HTTP/1.1


### POST
### Happy
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 0,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 22,
    "attack": 22,
    "defense": 22,
    "specialAttack": 22,
    "specialDefense": 22,
    "speed": 22
}

###
GET {{url}}user/2 HTTP/1.1

### Missing/Out of Range Fields/
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 0,
    "pokemonName": "",
    "appUserId": 2,
    "maxHp": 22,
    "attack": 22,
    "defense": 22,
    "specialAttack": 22,
    "specialDefense": 22,
    "speed": 22
}
### 
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 0,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 33,
    "attack": 22,
    "defense": 22,
    "specialAttack": 22,
    "specialDefense": 22,
    "speed": 22
}

### Preset pokemonInstanceId
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 3,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 22,
    "attack": 22,
    "defense": 22,
    "specialAttack": 22,
    "specialDefense": 22,
    "speed": 22
}

### PUT
### HAPPY
PUT {{url}}7 HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 7,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 11,
    "attack": 11,
    "defense": 11,
    "specialAttack": 11,
    "specialDefense": 11,
    "speed": 11
}

###
GET {{url}}user/2 HTTP/1.1

### UNHAPPY
### CONFLICT
PUT {{url}}7 HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 3,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 11,
    "attack": 11,
    "defense": 11,
    "specialAttack": 11,
    "specialDefense": 11,
    "speed": 11
}

### Missing/Out Of Range Fields
PUT {{url}}7 HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 7,
    "pokemonName": "",
    "appUserId": 2,
    "maxHp": 11,
    "attack": 11,
    "defense": 11,
    "specialAttack": 11,
    "specialDefense": 11,
    "speed": 11
}

### 
PUT {{url}}7 HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 7,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 33,
    "attack": 11,
    "defense": 11,
    "specialAttack": 11,
    "specialDefense": 11,
    "speed": 11
}

### Not Found
PUT {{url}}123 HTTP/1.1
Content-Type: application/json

{
    "pokemonInstanceId": 123,
    "pokemonName": "Test",
    "appUserId": 2,
    "maxHp": 11,
    "attack": 11,
    "defense": 11,
    "specialAttack": 11,
    "specialDefense": 11,
    "speed": 11
}

### DELETE
### Happy
DELETE  {{url}}7 HTTP/1.1

###
GET {{url}}user/2 HTTP/1.1

### Unhappy
### Not Found
DELETE  {{url}}7 HTTP/1.1
